### ISSUE TITLE
[Test] Query: node

### ISSUE THREAD

**Issue by davibauer** [hack-a-chain-software/indexer-kadena#116]
# Execution Times

Kadena: 
- [x] 556.43 ms

Hack-a-chain:
- [ ] 516.02 ms

# Results

- [ ] Hack-a-chain endpoint - Got an error:
```
{
    "errors": [
        {
            "message": "Fields \"chainId\" conflict because they return conflicting types \"BigInt\" and \"BigInt!\". Use different aliases on the fields to fetch both if this was intentional.",
            "locations": [
                {
                    "line": 5,
                    "column": 13
                },
                {
                    "line": 8,
                    "column": 13
                }
            ],
            "extensions": {
                "code": "GRAPHQL_VALIDATION_FAILED",
                "stacktrace": [
                    "GraphQLError: Fields \"chainId\" conflict because they return conflicting types \"BigInt\" and \"BigInt!\". Use different aliases on the fields to fetch both if this was intentional.",
                    "    at Object.SelectionSet (/app/node_modules/graphql/validation/rules/OverlappingFieldsCanBeMergedRule.js:67:11)",
                    "    at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)",
                    "    at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)",
                    "    at visit (/app/node_modules/graphql/language/visitor.js:197:21)",
                    "    at validate (/app/node_modules/graphql/validation/validate.js:91:24)",
                    "    at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)",
                    "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
                    "    at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)",
                    "    at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)",
                    "    at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)"
                ]
            }
        },
        {
            "message": "Fields \"chainId\" conflict because they return conflicting types \"BigInt\" and \"BigInt!\". Use different aliases on the fields to fetch both if this was intentional.",
            "locations": [
                {
                    "line": 5,
                    "column": 13
                },
                {
                    "line": 29,
                    "column": 13
                }
            ],
            "extensions": {
                "code": "GRAPHQL_VALIDATION_FAILED",
                "stacktrace": [
                    "GraphQLError: Fields \"chainId\" conflict because they return conflicting types \"BigInt\" and \"BigInt!\". Use different aliases on the fields to fetch both if this was intentional.",
                    "    at Object.SelectionSet (/app/node_modules/graphql/validation/rules/OverlappingFieldsCanBeMergedRule.js:67:11)",
                    "    at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)",
                    "    at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)",
                    "    at visit (/app/node_modules/graphql/language/visitor.js:197:21)",
                    "    at validate (/app/node_modules/graphql/validation/validate.js:91:24)",
                    "    at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)",
                    "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
                    "    at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)",
                    "    at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)",
                    "    at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)"
                ]
            }
        },
        {
            "message": "Cannot query field \"incrementedId\" on type \"Event\".",
            "locations": [
                {
                    "line": 11,
                    "column": 13
                }
            ],
            "extensions": {
                "code": "GRAPHQL_VALIDATION_FAILED",
                "stacktrace": [
                    "GraphQLError: Cannot query field \"incrementedId\" on type \"Event\".",
                    "    at Object.Field (/app/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)",
                    "    at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)",
                    "    at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)",
                    "    at visit (/app/node_modules/graphql/language/visitor.js:197:21)",
                    "    at validate (/app/node_modules/graphql/validation/validate.js:91:24)",
                    "    at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)",
                    "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
                    "    at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)",
                    "    at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)",
                    "    at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)"
                ]
            }
        },
        {
            "message": "Cannot query field \"parameterText\" on type \"Event\". Did you mean \"parameters\"?",
            "locations": [
                {
                    "line": 15,
                    "column": 13
                }
            ],
            "extensions": {
                "code": "GRAPHQL_VALIDATION_FAILED",
                "stacktrace": [
                    "GraphQLError: Cannot query field \"parameterText\" on type \"Event\". Did you mean \"parameters\"?",
                    "    at Object.Field (/app/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)",
                    "    at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)",
                    "    at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)",
                    "    at visit (/app/node_modules/graphql/language/visitor.js:197:21)",
                    "    at validate (/app/node_modules/graphql/validation/validate.js:91:24)",
                    "    at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)",
                    "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
                    "    at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)",
                    "    at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)",
                    "    at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)"
                ]
            }
        },
        {
            "message": "Cannot query field \"requestKey\" on type \"Event\". Did you mean \"requestkey\"?",
            "locations": [
                {
                    "line": 18,
                    "column": 13
                }
            ],
            "extensions": {
                "code": "GRAPHQL_VALIDATION_FAILED",
                "stacktrace": [
                    "GraphQLError: Cannot query field \"requestKey\" on type \"Event\". Did you mean \"requestkey\"?",
                    "    at Object.Field (/app/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)",
                    "    at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)",
                    "    at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)",
                    "    at visit (/app/node_modules/graphql/language/visitor.js:197:21)",
                    "    at validate (/app/node_modules/graphql/validation/validate.js:91:24)",
                    "    at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)",
                    "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
                    "    at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)",
                    "    at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)",
                    "    at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)"
                ]
            }
        },
        {
            "message": "Unknown type \"NonFungibleAccount\". Did you mean \"FungibleAccount\", \"NonFungibleChainAccount\", \"NonFungibleToken\", or \"FungibleChainAccount\"?",
            "locations": [
                {
                    "line": 74,
                    "column": 16
                }
            ],
            "extensions": {
                "code": "GRAPHQL_VALIDATION_FAILED",
                "stacktrace": [
                    "GraphQLError: Unknown type \"NonFungibleAccount\". Did you mean \"FungibleAccount\", \"NonFungibleChainAccount\", \"NonFungibleToken\", or \"FungibleChainAccount\"?",
                    "    at Object.NamedType (/app/node_modules/graphql/validation/rules/KnownTypeNamesRule.js:65:11)",
                    "    at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)",
                    "    at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)",
                    "    at visit (/app/node_modules/graphql/language/visitor.js:197:21)",
                    "    at validate (/app/node_modules/graphql/validation/validate.js:91:24)",
                    "    at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)",
                    "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
                    "    at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)",
                    "    at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)",
                    "    at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)"
                ]
            }
        },
        {
            "message": "Unknown type \"MinerKey\".",
            "locations": [
                {
                    "line": 78,
                    "column": 16
                }
            ],
            "extensions": {
                "code": "GRAPHQL_VALIDATION_FAILED",
                "stacktrace": [
                    "GraphQLError: Unknown type \"MinerKey\".",
                    "    at Object.NamedType (/app/node_modules/graphql/validation/rules/KnownTypeNamesRule.js:65:11)",
                    "    at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)",
                    "    at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)",
                    "    at visit (/app/node_modules/graphql/language/visitor.js:197:21)",
                    "    at validate (/app/node_modules/graphql/validation/validate.js:91:24)",
                    "    at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)",
                    "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
                    "    at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)",
                    "    at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)",
                    "    at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)"
                ]
            }
        }
    ]
}
```

- Kadena endpoint - Got json result:
```
{
    "data": {
        "node": {
            "chainId": 2,
            "id": "QmxvY2s6Z19vQjdIT2JuYk14dWxGUXlSYWg0a0hVYnNXenhlUVlIMnRDbnJsUk83UQ=="
        }
    },
    "extensions": {}
}
```

**Reference Query**
https://graph.kadena.network/graphql
```
query Node {
    node(id: "QmxvY2s6Z19vQjdIT2JuYk14dWxGUXlSYWg0a0hVYnNXenhlUVlIMnRDbnJsUk83UQ==") {
        id
        ... on Block {
            chainId
        }
        ... on Event {
            chainId
            height
            id
            incrementedId
            moduleName
            name
            orderIndex
            parameterText
            parameters
            qualifiedName
            requestKey
        }
        ... on FungibleAccount {
            accountName
            fungibleName
            id
            totalBalance
        }
        ... on Transfer {
            amount
            blockHash
            chainId
            creationTime
            height
            id
            moduleHash
            moduleName
            orderIndex
            receiverAccount
            requestKey
            senderAccount
        }
        ... on Transaction {
            hash
            id
            result {
                ... on TransactionResult {
                    badResult
                    continuation
                    eventCount
                    gas
                    goodResult
                    height
                    logs
                    metadata
                    transactionId
                }
            }
        }
        ... on Signer {
            address
            id
            pubkey
            scheme
        }
        ... on NonFungibleTokenBalance {
            accountName
            balance
            id
            tokenId
            version
        }
        ... on NonFungibleChainAccount {
            accountName
            id
        }
        ... on NonFungibleAccount {
            accountName
            id
        }
        ... on MinerKey {
            blockHash
            id
            key
        }
        ... on FungibleChainAccount {
            accountName
            fungibleName
            id
        }
    }
}
```

**Comment by mschead** [comment]
@davibauer a few things to consider for this query
* the attributes `incrementedId` and `parameterText` were removed from Event type.
* the MineyKey type was removed
* the NonFungibleTokenBalance, NonFungibleChainAccount, NonFungibleAccount types will be implemented.
