### ISSUE TITLE
[Test] Query: blocksFromHeight

### ISSUE THREAD

**Issue by davibauer** [hack-a-chain-software/indexer-kadena#99]
**Fail Results**

- [ ] Column Block.endHeight does not exist

```
{
    "errors": [
        {
            "message": "column Block.endHeight does not exist",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "blocksFromHeight"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "stacktrace": [
                    "Error",
                    "    at Query.run (/app/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)",
                    "    at /app/node_modules/sequelize/lib/sequelize.js:315:28",
                    "    at async PostgresQueryInterface.select (/app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)",
                    "    at async Block.findAll (/app/node_modules/sequelize/lib/model.js:1140:21)",
                    "    at async BlockDbRepository.getBlocksBetweenHeights (/app/dist/kadena-server/repository/infra/repository/block-db-repository.js:56:22)",
                    "    at async Object.blocksFromHeightQueryResolver [as blocksFromHeight] (/app/dist/kadena-server/resolvers/query/blocks-from-height-query-resolver.js:6:20)"
                ]
            }
        }
    ],
    "data": null
}
```

**Reference Query**
https://graph.kadena.network/graphql
```
query MyQuery {
  blocksFromHeight(startHeight: 5126571, endHeight: 5126580) {
    edges {
      node {
        chainId
        creationTime
        difficulty
        epoch
        hash
        height
        nonce
      }
    }
    pageInfo {
      hasNextPage
    }
  }
}
```

**Comment by mschead** [comment]
Found the issue. It will be fixed on the next deploy.
